python  ./run_squad.py \
  --model_type albert \
	--do_eval \
	--model_name_or_path ./ \
  --train_file $2 \
	--predict_file $2 \
	--max_seq_length 384 \
	--per_gpu_eval_batch_size 100 \
  --output_dir ./ \
  --output_file_name $3 \
  --config_name ./config.json \
  --tokenizer_name ./tokenizer_config.json \
